const COLOR_PRIMARY = '#0A8ED9';
const COLOR_SECONDARY = '#F7F7FC';
const COLOR_DIVIDER = '#EBEBF0';
const COLOR_DISABLED = '#ADB5BD';
const COLOR_GRAY = '#858585';
const COLOR_BLACK = '#000000';
const COLOR_WHITE = '#FFFFFF';

export {
  COLOR_PRIMARY,
  COLOR_SECONDARY,
  COLOR_DISABLED,
  COLOR_DIVIDER,
  COLOR_GRAY,
  COLOR_BLACK,
  COLOR_WHITE,
};
